// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CanAutoDNSSEC-0]
	_ = x[CanGetZones-1]
	_ = x[CanUseAKAMAICDN-2]
	_ = x[CanUseAlias-3]
	_ = x[CanUseAzureAlias-4]
	_ = x[CanUseCAA-5]
	_ = x[CanUseDHCID-6]
	_ = x[CanUseDS-7]
	_ = x[CanUseDSForChildren-8]
	_ = x[CanUseLOC-9]
	_ = x[CanUseNAPTR-10]
	_ = x[CanUseOPENPGPKEY-11]
	_ = x[CanUsePTR-12]
	_ = x[CanUseRoute53Alias-13]
	_ = x[CanUseSOA-14]
	_ = x[CanUseSRV-15]
	_ = x[CanUseSSHFP-16]
	_ = x[CanUseTLSA-17]
	_ = x[CantUseNOPURGE-18]
	_ = x[DocCreateDomains-19]
	_ = x[DocDualHost-20]
	_ = x[DocOfficiallySupported-21]
}

const _Capability_name = "CanAutoDNSSECCanGetZonesCanUseAKAMAICDNCanUseAliasCanUseAzureAliasCanUseCAACanUseDHCIDCanUseDSCanUseDSForChildrenCanUseLOCCanUseNAPTRCanUseOPENPGPKEYCanUsePTRCanUseRoute53AliasCanUseSOACanUseSRVCanUseSSHFPCanUseTLSACantUseNOPURGEDocCreateDomainsDocDualHostDocOfficiallySupported"

var _Capability_index = [...]uint16{0, 13, 24, 39, 50, 66, 75, 86, 94, 113, 122, 133, 149, 158, 176, 185, 194, 205, 215, 229, 245, 256, 278}

func (i Capability) String() string {
	if i >= Capability(len(_Capability_index)-1) {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[i]:_Capability_index[i+1]]
}
